const projects = [
  {
    id: 1,
    title: 'VIVBAG',
    category: 'HTML/CSS/JS',
    gitIcon: 'https://github.com/bant095/Responsive-Bags-Website.git',
    liveIcon: 'https://bagsecommercepage.netlify.app/',
    img: 'https://ik.imagekit.io/gru3qfrss/box1.JPG?',
    desc: `VIVBAG is a Fashion Bag Company that Unleash Your Style with Fashion Bag. The brand believe that style is a powerful form of self-expression. `,
  },
  {
    id: 2,
    title: 'PadiPay',
    category: 'REACT',
    gitIcon: 'https://github.com/bant095/padipayApp-Frontend.git',
    liveIcon: 'padipay-app.vercel.app/',
    img: 'https://ik.imagekit.io/gru3qfrss/padipay%20new%20landing.JPG?',
    desc: `PadiPay is a peer to peer lending platform that connect borrowers and lenders together.  `,
  },
  {
    id: 3,
    title: 'Ardilla Investment',
    category: 'HTML/CSS/JS',
    gitIcon: 'https://github.com/bant095/Ardilla-Webpage.git',
    liveIcon: 'https://ardillawebpage.netlify.app/',
    img: 'https://ik.imagekit.io/gru3qfrss/box2.JPG?',
    desc: `Ardilla is an investment platform that helps you save and invest in achieving your financial goals, we have the most flexible and seamless way to grow your funds.`,
  },
  {
    id: 4,
    title: 'Sneakers Store',
    category: 'HTML/CSS/JS',
    gitIcon: 'https://github.com/bant095/Sneakers-Store.git',
    liveIcon: 'https://sneakersstoreweb.netlify.app/',
    img: 'https://ik.imagekit.io/gru3qfrss/box4.JPG?',
    desc: `Step into style with Sneakers Store. Discover a wide selection of trendy and comfortable footwear for every occasion. `,
  },
  {
    id: 5,
    title: 'FreshPicks Farms',
    category: 'HTML/CSS/JS',
    gitIcon:
      'https://github.com/bant095/Responsive-Fruits-And-Vegetables-Website.git',
    liveIcon: 'https://fruitsandvegetableswebsite.netlify.app/',
    img: 'https://ik.imagekit.io/gru3qfrss/box3.JPG?',
    desc: `FreshPicks Farms is a family-owned farm dedicated to delivering the freshest, locally grown produce straight from our fields to your table.  `,
  },
  {
    id: 6,
    title: 'Fylo stores',
    category: 'HTML/CSS/JS',
    gitIcon: 'https://github.com/bant095/Fylo-Landing-page.git',
    liveIcon: 'https://fyloproduct.netlify.app/',
    img: 'https://ik.imagekit.io/gru3qfrss/box5.JPG?',
    desc: `Fylo stores your most important files in one secure location. Access them wherever you need, share and collaborate with friends, family, and co-workers.`,
  },
];
export default projects;
